lead_qualification_task:
  description: >
    Analyze each lead based on the company you represent: {company_name} and its description: {company_description}.
    Evaluate whether the lead's company would be a good fit for your offerings by considering:
    1. Industry alignment with your company's target markets
    2. Company size and growth potential
    3. Potential use cases for your products/services
    4. Decision-maker seniority and influence
    5. Current tech stack or solutions they might be using
    Cleanse, normalize, and deduplicate the lead records as needed. Use the web to find more information about the lead if needed. There are no exceptions to this and ALL leads must be classified. 
  expected_output: >
    A JSON-formatted list of ALL lead records where each record includes:
    1. An additional field for lead score (0-100)
    2. Classification (HOT, WARM, or COLD)
    3. Brief reasoning for the classification
    4. Potential value alignment between your company and the lead
    5. Recommended approach for initial outreach
    All formatted and ready for prioritization in the sales process. There are no exceptions to this and ALL leads must be classified.

# prospect_research_task:
#   description: >
#     Enrich each lead with detailed company and decision-maker information by gathering data from LinkedIn, websites, and news articles.
#   expected_output: >
#     An enriched dataset where each lead record includes company details and relevant decision-maker insights.

# email_outreach_task:
#   description: >
#     Generate personalized outreach emails and messages using CRM data and interaction history via GPT-based templates.
#   expected_output: >
#     A list of customized email messages for each lead, formatted in plain text.

# sales_call_prep_task:
#   description: >
#     Compile essential information from CRM, emails, and LinkedIn profiles to create one-page call briefs for sales calls.
#   expected_output: >
#     A one-page summary for each lead highlighting key details for effective call preparation.

# objection_handling_task:
#   description: >
#     Analyze historical sales data to provide real-time objection handling suggestions during calls.
#   expected_output: >
#     A list of recommended responses for common objections, structured for quick reference.

# proposal_quote_task:
#   description: >
#     Automatically generate tailored proposals and pricing quotes by integrating data from product catalogs, CRM, and customer details.
#   expected_output: >
#     Detailed proposal and quote documents for each customer, covering pricing and custom recommendations.

# competitor_analysis_task:
#   description: >
#     Gather and summarize competitor information through web scraping and market research, highlighting key competitive insights.
#   expected_output: >
#     A summary report of competitor strengths, weaknesses, and market positioning.

# sales_forecasting_task:
#   description: >
#     Utilize historical deal data and current pipeline metrics to predict deal success and forecast future revenue.
#   expected_output: >
#     A forecasting model output with predicted success rates and revenue estimates for ongoing deals.

# followup_nurture_task:
#   description: >
#     Implement and schedule follow-up communications to nurture leads based on CRM data and email tracking.
#   expected_output: >
#     A scheduled set of follow-up messages with corresponding time triggers and content drafts.

# customer_success_upsell_task:
#   description: >
#     Analyze customer usage values, support tickets, and CRM insights to flag accounts with upsell or renewal potential.
#   expected_output: >
#     A report detailing accounts flagged for upsell/renewal along with the metrics used for their assessment.
