lead_qualification_task:
  description: >
    Analyze each lead based on the company you represent: {company_name} and its description: {company_description}.
    Evaluate whether the lead's company would be a good fit for your offerings by considering:
    1. Industry alignment with your company's target markets
    2. Company size and growth potential
    3. Potential use cases for your products/services
    4. Decision-maker seniority and influence
    5. Current tech stack or solutions they might be using
    Cleanse, normalize, and deduplicate the lead records as needed. Use the web to find more information about the lead if needed. **ALL** leads must be classified and there are no exceptions to these rules. 
  expected_output: >
    A JSON-formatted list of ALL lead records where each record includes:
    1. Lead name 
    2. Company name
    3. Email address
    4. Phone number
    5. An additional field for lead score (0-100)
    6. Classification (HOT, WARM, or COLD)
    7. Brief reasoning for the classification
    8. Potential value alignment between your company and the lead
    9. Recommended approach for initial outreach
    All formatted and ready for prioritization in the sales process. **ALL** leads must be classified and there are no exceptions to these rules.

prospect_research_task:
  description: >
    Enrich **ALL** HOT and WARM leads with detailed company and decision-maker information by gathering data from the web.
    For each high-priority lead, research and collect:
    1. Company information: industry, size, revenue, funding, growth trajectory, tech stack, products/services
    2. Lead name details: role, responsibilities, career history, educational background, social media presence
    3. Recent company news, press releases, or significant events
    4. Potential pain points or challenges the company might be facing
    5. Current solutions or vendors they might be using
    6. Evidence of why the lead needs your solution NOW 
    Focus on information that would be most relevant for personalized outreach and understanding potential fit.
    
    IMPORTANT TIME MANAGEMENT GUIDELINES:
    - Analyze ONLY HOT and WARM leads - completely ignore COLD leads
    - Allocate research time proportionally based on lead classification: HOT, WARM 
    - For each lead, spend no more than 2-3 web searches to gather essential information
    - If specific information is difficult to find after a reasonable effort, note it as "Information not readily available" and move on
    - Ensure ALL HOT and WARM leads receive attention - do not skip any high-priority leads
    - Focus on quality over quantity - a few highly relevant insights are more valuable than extensive general information
  expected_output: >
    A JSON-formatted list of enriched HOT and WARM lead records where each record includes:
    1. Detailed company profile with industry, size, revenue (if available), products/services
    2. Lead name insights including role details, background, and areas of responsibility
    3. Recent company developments or news that might create sales opportunities
    4. Identified pain points or challenges that your solution could address
    5. Current solutions or competitors' products they might be using
    6. Timely evidence of why the lead needs your solution NOW (based on latest news, market trends, or digital footprints)
    7. Recommended talking points for initial outreach based on the research
    The enriched data should be structured and formatted for easy consumption by the Email & Outreach Agent.
    
    For any information that could not be found after a reasonable search effort, include a note stating "Information not readily available" rather than leaving fields empty.

email_outreach_task:
  description: >
    Generate highly personalized and compelling email outreach for ALL HOT and WARM leads using the enriched data 
    provided by the Prospect Research Agent. For each high-potential lead, create emails that:
    
    1. Have eye-catching subject lines that reference specific company challenges or opportunities
    2. Establish immediate relevance with personalized opening lines referencing recent news or achievements
    3. Clearly articulate value proposition in context of their specific business needs
    4. Demonstrate understanding of their pain points with specific examples
    5. Include social proof or case studies relevant to their industry
    6. Feature a clear, low-friction call-to-action
    7. Maintain professional but conversational tone with natural language
    
    Tailor the messaging style based on the lead's seniority, industry, and cultural context. HOT leads should receive 
    extra attention with more deeply personalized content. For each lead, leverage all available information:
    
    - Company profile details (industry, size, challenges)
    - Lead's role and background information
    - Pain points identified in research
    - Recent company news or developments
    - Competitive landscape and current solutions
    - Urgency drivers that make your solution timely
    
    The goal is to create emails that feel individually crafted, not mass-produced, with messaging that directly 
    addresses why your solution is uniquely valuable to their specific situation right now.
  expected_output: >
    A JSON-formatted list of email templates for ALL HOT and WARM leads where each template includes:
    
    1. Lead name and company
    2. Classification (HOT or WARM)
    3. Compelling subject line
    4. Personalized email body with appropriate greeting, introduction, value proposition, pain point addressing, social proof, and call-to-action
    5. Suggested follow-up timing (immediate, 3 days, 1 week)
    6. Alternative contact channels if available (LinkedIn, etc.)
    7. Recommended A/B test variations for subject lines or opening paragraphs
    
    Each email should be fully ready to send with all placeholder text replaced with specific, personalized content.
    The output should prioritize quality over quantity, with special attention given to HOT leads to maximize 
    conversion potential. All emails must maintain a professional tone while being conversational enough to stand 
    out from typical sales messages.

# sales_call_prep_task:
#   description: >
#     Compile essential information from CRM, emails, and LinkedIn profiles to create one-page call briefs for sales calls.
#   expected_output: >
#     A one-page summary for each lead highlighting key details for effective call preparation.

# objection_handling_task:
#   description: >
#     Analyze historical sales data to provide real-time objection handling suggestions during calls.
#   expected_output: >
#     A list of recommended responses for common objections, structured for quick reference.

# proposal_quote_task:
#   description: >
#     Automatically generate tailored proposals and pricing quotes by integrating data from product catalogs, CRM, and customer details.
#   expected_output: >
#     Detailed proposal and quote documents for each customer, covering pricing and custom recommendations.

# competitor_analysis_task:
#   description: >
#     Gather and summarize competitor information through web scraping and market research, highlighting key competitive insights.
#   expected_output: >
#     A summary report of competitor strengths, weaknesses, and market positioning.

# sales_forecasting_task:
#   description: >
#     Utilize historical deal data and current pipeline metrics to predict deal success and forecast future revenue.
#   expected_output: >
#     A forecasting model output with predicted success rates and revenue estimates for ongoing deals.

# followup_nurture_task:
#   description: >
#     Implement and schedule follow-up communications to nurture leads based on CRM data and email tracking.
#   expected_output: >
#     A scheduled set of follow-up messages with corresponding time triggers and content drafts.

# customer_success_upsell_task:
#   description: >
#     Analyze customer usage values, support tickets, and CRM insights to flag accounts with upsell or renewal potential.
#   expected_output: >
#     A report detailing accounts flagged for upsell/renewal along with the metrics used for their assessment.
